
project_id = "lqfhhqhswdqpsliskxrr"

[functions.generate-strategy]
verify_jwt = false

[functions.get-fmp-key]
verify_jwt = true

[functions.get-taapi-key]
verify_jwt = true

[functions.openai-chat]
verify_jwt = false

