
project_id = "lqfhhqhswdqpsliskxrr"

[functions.delete-user-account]
verify_jwt = true

[functions.generate-strategy]
verify_jwt = true

[functions.get-fmp-key]
verify_jwt = true

[functions.get-taapi-key]
verify_jwt = true

[functions.get-turnstile-key]
verify_jwt = false

[functions.openai-chat]
verify_jwt = true

[functions.send-email-notification]
verify_jwt = true

[functions.send-discord-notification]
verify_jwt = true

[functions.send-telegram-notification]
verify_jwt = true

[functions.verify-discord-webhook]
verify_jwt = true

[functions.verify-telegram-bot]
verify_jwt = true
